apiVersion: v1
kind: Service
metadata:
  name: product-api-stable
  namespace: product-api
spec:
  selector:
    app: product-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: product-api-canary
#   namespace: product-api
# spec:
#   selector:
#     app: product-api
#   ports:
#     - name: http
#       protocol: TCP
#       port: 8080