#@ load("@ytt:data", "data")
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-petclinic
  namespace: spring-petclinic
spec:
  rules:
  - host: #@ data.values.ingress_hostname
    http:
      paths:
      - backend:
          serviceName: spring-petclinic
          servicePort: http
        path: /
  tls:
  - hosts:
    - #@ data.values.ingress_hostname
    secretName: spring-petclinic-tls