apiVersion: v1
kind: Namespace
metadata:
  name: minibroker
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minibroker
  namespace: minibroker
spec:
  helmVersion: v3
  targetNamespace: minibroker
  releaseName: minibroker
  wait: true
  test:
    enable: true
  chart:
    repository: https://minibroker.blob.core.windows.net/charts
    name: minibroker
    version: "0.3.1"
  values:
    deployServiceCatalog: false
    defaultNamespace: minibroker