#@ load("@ytt:data", "data")


apiVersion: v1
kind: Namespace
metadata:
  name: images
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: product-api
  namespace: images
spec:
  tag: #@ data.values.product_api_image
  serviceAccount: tbs-service-account
  builder:
    name: base
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/techgnosis/product-api.git
      revision: demo

