#@ load("@ytt:data", "data")
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sockshop
  namespace: sockshop
spec:
  rules:
  - host: #@ data.values.ingress_hostname
    http:
      paths:
      - backend:
          serviceName: front-end
          servicePort: 80
        path: /
  tls:
  - hosts:
    - #@ data.values.ingress_hostname
    secretName: sockshop-tls