source:
  repo:
    kind: HELM
    url: https://charts.bitnami.com/bitnami
target:
  repoName: nginx-ingress-controller
  containerRegistry: harbor.lab.home
  containerRepository: library
  repo:
    kind: HARBOR
    url: https://harbor.lab.home/chartrepo/library
    auth:
      username: admin
      password: Harbor12345